# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MIT

---                                                    
apiVersion: apps/v1                                    
kind: Deployment
metadata:
  name: emojify-facebox
  labels:
    app: emojify-facebox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: emojify-facebox
  template:
    metadata:
      labels:
        app: emojify-facebox
      annotations:
        "consul.hashicorp.com/connect-inject": "true"
    spec:
      containers:
      - name: emojify-facebox
        image: "machinebox/facebox"
        ports:
        - containerPort: 8080
        env:
        - name: MB_KEY
          valueFrom:
            secretKeyRef:
              name: emojify
              key: mb_key
        - name: MB_ADDRESS
          value: "0.0.0.0"
        - name: MB_PORT
          value: "8080"
