---
apiVersion: v1
kind: Service
metadata:
  name: emojify-api
spec:
  selector:
    app: emojify-api
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 9090

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: emojify-api-cache
  labels:
    app: emojify-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: emojify-api
  template:
    metadata:
      labels:
        app: emojify-api
      annotations:
        "prometheus_io_scrape": "true"
    spec:
      containers:
      - name: emojify-api
        image: "nicholasjackson/emojify-api:v0.8.0"
        imagePullPolicy: Always
        command: ["/service/emojify-api"]
        args: [
          "-allow-origin=*",
          "-authn-disable=true",
          "-bind-address=0.0.0.0:9090",
          "-statsd-server=127.0.0.1:9125",
          "-cache-address=emojify-cache:80",
          "-facebox-address=emojify-facebox:80",
          "-cache-error-rate=0.2", // Requests to the cache error 100% of the time
          "-path=/",
        ]
        ports:
        - containerPort: 9090
        livenessProbe:
          httpGet:
            path: /health
            port: 9090
          initialDelaySeconds: 10
          periodSeconds: 30
        resources:
          limits:
            cpu: 300m
          requests:
            cpu: 100m
            memory: 100Mi

      - name: prometheus-statsd
        image: prom/statsd-exporter:latest
        ports:
          - name: metrics
            containerPort: 9102
        resources:
          limits:
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 100Mi
