# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MIT

---
apiVersion: v1
kind: Service
metadata:
  name: emojify-cache
spec:
  selector:
    app: emojify-cache
  ports:
  - protocol: TCP
    port: 80
    targetPort: 9090

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: emojify-cache
  labels:
    app: emojify-cache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: emojify-cache
  template:
    metadata:
      labels:
        app: emojify-cache
      annotations:
        "prometheus_io_scrape": "true"
    spec:
      containers:
      - name: emojify-cache
        image: "nicholasjackson/emojify-cache:v0.4.3"
        ports:
        - containerPort: 9090
        env:
        - name: BIND_ADDRESS
          value: "0.0.0.0"
        - name: STATSD_ADDRESS
          value: "localhost:9125"

      - name: prometheus-statsd
        image: prom/statsd-exporter:latest
        ports:
          - name: metrics
            containerPort: 9102
        resources:
          limits:
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 100Mi
