---
apiVersion: v1
kind: Service
metadata:
  name: emojify-facebox
spec:
  selector:
    app: emojify-facebox
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080

---                                                    
apiVersion: apps/v1                                    
kind: Deployment
metadata:
  name: emojify-facebox
  labels:
    app: emojify-facebox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: emojify-facebox
  template:
    metadata:
      labels:
        app: emojify-facebox
      annotations:
        "prometheus_io_scrape": "true"
    spec:
      containers:
      - name: emojify-facebox
        image: "machinebox/facebox"
        ports:
        - containerPort: 8080
        env:
        - name: MB_KEY
          valueFrom:
            secretKeyRef:
              name: emojify
              key: mb_key
        - name: MB_ADDRESS
          value: "0.0.0.0"
        - name: MB_PORT
          value: "8080"

      - name: prometheus-statsd
        image: prom/statsd-exporter:latest
        ports:
          - name: metrics
            containerPort: 9102
        resources:
          limits:
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 100Mi