# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MIT

---
apiVersion: v1
kind: Service
metadata:
  name: emojify-ingress
spec:
  type: NodePort
  selector:
    app: emojify-ingress
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30000

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: emojify-ingress-configmap
data:
  config: |
    events {
      worker_connections  1024;
    }

    http {
      upstream emojify-website {
        keepalive 100;
        server emojify-website:80;
      }
      upstream emojify-api {
        keepalive 100;
        server emojify-api:80;
      }

      server {
        location / {
          proxy_http_version 1.1;
          proxy_pass http://emojify-website;
          proxy_set_header Host $host;
        }

        location ~ ^/api(/.*)?$ {
          proxy_http_version 1.1;
          proxy_pass http://emojify-api$1$is_args$args;
          proxy_pass_request_headers on;
        }
      }
    }

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: emojify-ingress
  labels:
    app: emojify-ingress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: emojify-ingress
  template:
    metadata:
      name: emojify-ingress
      labels:
        app: emojify-ingress
      annotations:
        "prometheus_io_scrape": "true"
    spec:
      volumes:
      - name: config
        configMap:
          name: emojify-ingress-configmap
          items:
          - key: config
            path: nginx.conf
      containers:
      - name: emojify-ingress
        image: nginx:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        volumeMounts:
        - name: config
          mountPath: /etc/nginx/

      - name: prometheus-statsd
        image: prom/statsd-exporter:latest
        ports:
          - name: metrics
            containerPort: 9102
        resources:
          limits:
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 100Mi
