{
 "title": "API",
 "tags": [ "emojify" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "API errors/s",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(api_service_emojify_called_count{status!=\"200\"}[1m])+rate(api_service_cache_called_count{status!=\"200\"}[1m]))"
    }
   ]
  },
  {
   "title": "API requests/s",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(api_service_emojify_called_count{status=\"200\"}[1m])+rate(api_service_cache_called_count{status=\"200\"}[1m]))",
     "legendFormat": "Success"
    }
   ]
  },
  {
   "title": "POD Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{container_name!=\"POD\",name=~\"^k8s_.*\",pod_name=~\"emojify-api-.*\"}) by (container_name)"
    }
   ]
  },
  {
   "title": "Pod CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate (container_cpu_usage_seconds_total{container_name!=\"POD\",pod_name=~\"emojify-api-.*\",name=~\"^k8s_.*\"}[1m])) by(container_name)"
    }
   ]
  },
  {
   "title": "Envoy Authz",
   "type": "graph",
   "gridPos": { "h": 9, "w": 19, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(envoy_ext_authz_connect_authz_ok{label_app=\"emojify-api\"}[1m])",
     "legendFormat": "{{name}}-{{ip}}"
    },
    {
     "expr": "increase(envoy_ext_authz_connect_authz_error{label_app=\"emojify-api\"}[1m])",
     "legendFormat": "{{name}}-{{ip}}"
    }
   ]
  },
  {
   "title": "Envoy Authz Error",
   "type": "text",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 17 },
   "content": "# Authz\nEnvoy will close a connection which either timesout or returns an error state: [https://github.com/envoyproxy/envoy/issues/5023](https://github.com/envoyproxy/envoy/issues/5023)\n",
   "targets": [
    {
     "expr": "envoy_ext_authz_connect_authz_error"
    }
   ]
  },
  {
   "title": "Envoy Connections",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(envoy_http_downstream_cx_total{envoy_http_conn_manager_prefix=\"ingress_api\"}[1m])",
     "legendFormat": "total-{{name}}"
    },
    {
     "expr": "increase(envoy_http_downstream_cx_destroy_remote{envoy_http_conn_manager_prefix=\"ingress_api\"}[1m])",
     "legendFormat": "destroy-remote-{{name}}"
    },
    {
     "expr": "increase(envoy_http_downstream_cx_destroy_local{envoy_http_conn_manager_prefix=\"ingress_api\"}[1m])",
     "legendFormat": "destroy-local-{{name}}"
    }
   ]
  },
  {
   "title": "Envoy Inbound Requests (downstream)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(envoy_http_downstream_rq_xx{envoy_http_conn_manager_prefix=\"ingress_api\"}[30s])) by (controller_name,envoy_response_code_class)",
     "legendFormat": "{{controller_name}}-{{envoy_response_code_class}}xx"
    }
   ]
  },
  {
   "title": "Emojify API Request Duration /cache GET(ms)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rate(api_service_cache_called_sum[10s])/rate(api_service_cache_called_count[10s])",
     "legendFormat": "{{ip}}"
    }
   ]
  },
  {
   "title": "Emojify API Request Duration / POST (ms)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rate(api_service_emojify_called_sum[30s])/rate(api_service_emojify_called_count[30s])",
     "legendFormat": "{{ip}}"
    }
   ]
  },
  {
   "title": "Emojify API Request Duration /health GET (ms)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "increase(api_service_health_called_sum[1m])/rate(api_service_health_called_count[1m])",
     "legendFormat": "{{controller_name}}"
    }
   ]
  },
  {
   "title": "Emojify Face Detect Duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 67 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rate(api_service_emojify_find_faces_sum[30s])/rate(api_service_emojify_find_faces_count[30s])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Emojify Cache Hits",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 75 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(api_service_emojify_cache_check_count[30s])",
     "legendFormat": "{{name}}-{{status}}"
    }
   ]
  },
  {
   "title": "Health Checks",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 83 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(api_service_health_called_count[1m])",
     "legendFormat": "{{ip}}"
    }
   ]
  }
 ]
}