{
 "title": "lab04-API",
 "tags": [ "emojify" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "pod_name",
    "query": "query_result(sum(api_service_health_called_count)by(name))"
   }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "APIerrors/s",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(api_service_emojify_called_count{status!=\"200\"}[1m])+rate(api_service_cache_called_count{status!=\"200\"}[1m]))+sum(rate(api_service_error_injected[1m]))"
    }
   ]
  },
  {
   "title": "APIrequests/s",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(api_service_emojify_called_count{status=\"200\"}[1m])+rate(api_service_cache_called_count{status=\"200\"}[1m]))",
     "legendFormat": "Success"
    }
   ]
  },
  {
   "title": "PodCPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container_name!=\"POD\",pod_name=~\"emojify-api-.*\",name=~\"^k8s_.*\"}[1m]))by(container_name)"
    }
   ]
  },
  {
   "title": "PODMemory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{container_name!=\"POD\",name=~\"^k8s_.*\",pod_name=~\"emojify-api-.*\"})by(container_name)"
    }
   ]
  },
  { "title": "EnvoyStats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "EnvoyAuthz",
   "type": "graph",
   "gridPos": { "h": 9, "w": 19, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(envoy_ext_authz_connect_authz_ok{label_app=\"emojify-api\",name=~\"^$pod_name$\"}[1m]))",
     "legendFormat": "ok"
    },
    {
     "expr": "sum(increase(envoy_ext_authz_connect_authz_error{label_app=\"emojify-api\",name=~\"^$pod_name$\"}[1m]))",
     "legendFormat": "error"
    }
   ]
  },
  {
   "title": "EnvoyAuthzError",
   "type": "text",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 19 },
   "content": "#Authz\nEnvoywillcloseaconnectionwhicheithertimesoutorreturnsanerrorstate:[https://github.com/envoyproxy/envoy/issues/5023](https://github.com/envoyproxy/envoy/issues/5023)\n",
   "targets": [
    {
     "expr": "envoy_ext_authz_connect_authz_error"
    }
   ]
  },
  {
   "title": "EnvoyConnections-downstream",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(envoy_http_downstream_cx_total{envoy_http_conn_manager_prefix=\"ingress_api\",name=~\"^$pod_name$\"}[1m]))",
     "legendFormat": "total"
    },
    {
     "expr": "sum(increase(envoy_http_downstream_cx_active{envoy_http_conn_manager_prefix=\"ingress_api\",name=~\"^$pod_name$\"}[1m]))",
     "legendFormat": "active"
    },
    {
     "expr": "sum(increase(envoy_http_downstream_cx_destroy_remote{envoy_http_conn_manager_prefix=\"ingress_api\",name=~\"^$pod_name$\"}[1m]))",
     "legendFormat": "destroy-remote"
    },
    {
     "expr": "sum(increase(envoy_http_downstream_cx_destroy_local{envoy_http_conn_manager_prefix=\"ingress_api\",name=~\"^$pod_name$\"}[1m]))",
     "legendFormat": "destroy-local"
    }
   ]
  },
  {
   "title": "EnvoyInboundRequests(downstream)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(envoy_http_downstream_rq_xx{envoy_http_conn_manager_prefix=\"ingress_api\",name=~\"^$pod_name$\"}[30s]))by(envoy_response_code_class,name)",
     "legendFormat": "{{envoy_response_code_class}}xx-{{name}}"
    }
   ]
  },
  {
   "title": "EnvoyConnectionsDataTransferred(persecond)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_http_downstream_cx_tx_bytes_total{envoy_http_conn_manager_prefix=\"ingress_api\",name=~\"^$pod_name$\"}[30s]))by(name)",
     "legendFormat": "{{envoy_response_code_class}}xx-{{name}}"
    }
   ]
  },
  { "title": "ApplicationStatistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "EmojifyAPIRequestDuration/cacheGET(ms)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(rate(api_service_cache_called_sum{name=~\"^$pod_name$\"}[10s])/rate(api_service_cache_called_count{name=~\"^$pod_name$\"}[10s]))by(status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "EmojifyAPIRequestDuration/POST(ms)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(rate(api_service_emojify_called_sum{name=~\"^$pod_name$\"}[30s])/rate(api_service_emojify_called_count{name=~\"^$pod_name$\"}[30s]))by(status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "EmojifyAPIRequestDuration/healthGET(ms)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(rate(api_service_health_called_sum{name=~\"^$pod_name$\"}[1m])/rate(api_service_health_called_count{name=~\"^$pod_name$\"}[1m]))by(status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "EmojifyFaceDetectDuration",
   "type": "graph",
   "description": "TimetakenforupstreamfaceboxAPItodetectfacesinanimage",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 80 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(rate(api_service_emojify_find_faces_sum{name=~\"^$pod_name$\"}[30s])/rate(api_service_emojify_find_faces_count{name=~\"^$pod_name$\"}[30s]))by(status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "EmojifyCacheHits",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 88 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(api_service_emojify_cache_check_count{name=~\"^$pod_name$\"}[30s]))by(status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "HealthChecks",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 96 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(api_service_health_called_count[1m])",
     "legendFormat": "{{ip}}"
    }
   ]
  }
 ]
}
{
 "title": "lab04-Cache",
 "tags": [ "emojify" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "pod_name",
    "query": "query_result(sum(cache_service_cache_get)by(name))"
   }
  ]
 },
 "panels": [
  { "title": "GeneralStatistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cacherequests/s",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(cache_service_cache_get_count{status=\"200\"}[60s])+rate(cache_service_cache_put_count{status=\"200\"}[60s]))+sum(rate(cache_service_cache_exists_count{status=\"302\"}[60s]))"
    }
   ]
  },
  {
   "title": "Errors/s",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(cache_service_cache_exists{status=~\"5.*\"}[60s])+rate(cache_service_cache_put{status=~\"5.*\"}[60s])+rate(cache_service_cache_get{status=~\"5.*\"}[60s]))+sum(rate(cache_service_cache_exists_count{status=~\"5.*\"}[60s]))"
    }
   ]
  },
  {
   "title": "PodCPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container_name!=\"POD\",pod_name=~\"emojify-cache-.*\",name=~\"^k8s_.*\"}[1m]))by(container_name)",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "PodMemoryUsage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{container_name!=\"POD\",name=~\"^k8s_.*\",pod_name=~\"emojify-cache-.*\"})by(container_name)",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "EnvoyStatistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true
  },
  {
   "title": "CurrentEnvoyUpstreamConnections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(envoy_http_downstream_cx_total{envoy_http_conn_manager_prefix=\"ingress_cache\",name=~\"^$pod_name$\"}[1m])",
     "legendFormat": "total"
    },
    {
     "expr": "sum(increase(envoy_http_downstream_cx_active{envoy_http_conn_manager_prefix=\"ingress_cache\",name=~\"^$pod_name$\"}[1m]))",
     "legendFormat": "active"
    },
    {
     "expr": "sum(increase(envoy_http_downstream_cx_destroy_remote{envoy_http_conn_manager_prefix=\"ingress_cache\",name=~\"^$pod_name$\"}[1m]))",
     "legendFormat": "destroy-remote"
    },
    {
     "expr": "sum(increase(envoy_http_downstream_cx_destroy_local{envoy_http_conn_manager_prefix=\"ingress_cache\",name=~\"^$pod_name$\"}[1m]))",
     "legendFormat": "destroy-local"
    }
   ]
  },
  {
   "title": "EnvoyAuthz",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(envoy_ext_authz_connect_authz_ok{name=~\"emojify-cache.*\"}[30s])",
     "legendFormat": "{{name}}-ok"
    },
    {
     "expr": "rate(envoy_ext_authz_connect_authz_error{name=~\"emojify-cache.*\"}[30s])",
     "legendFormat": "{{name}}-error"
    }
   ]
  },
  {
   "title": "CacheSuccessgRPC",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(envoy_cluster_grpc_0{label_app=\"emojify-cache\"}[30s]))by(envoy_grpc_bridge_method)",
     "legendFormat": "{{envoy_grpc_bridge_method}}"
    }
   ]
  },
  {
   "title": "CacheFailuregRPC",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(envoy_cluster_grpc_failure{label_app=\"emojify-cache\"}[30s]))by(envoy_grpc_bridge_method)",
     "legendFormat": "{{envoy_grpc_bridge_method}}"
    }
   ]
  },
  {
   "title": "CacheNotFoundgRPC",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(envoy_cluster_grpc_5{label_app=\"emojify-cache\"}[30s]))by(envoy_grpc_bridge_method)",
     "legendFormat": "{{envoy_grpc_bridge_method}}"
    }
   ]
  },
  { "title": "ApplicationStatistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 } },
  {
   "title": "CacheGet(ms)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rate(cache_service_cache_get_sum[30s])/rate(cache_service_cache_get_count[30s])",
     "legendFormat": "{{name}}-{{status}}"
    }
   ]
  },
  {
   "title": "CachePut(ms)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rate(cache_service_cache_put_sum[30s])/rate(cache_service_cache_put_count[30s])",
     "legendFormat": "{{name}}-{{status}}"
    }
   ]
  },
  {
   "title": "Cacheinvalidation(ms)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "cache_service_cache_invalidate_sum/cache_service_cache_invalidate_count",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "CacheInvalidatedItems",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 72 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(cache_service_cache_invalidated[30s])",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}
{
 "title": "lab04-Ingress",
 "tags": [ "emojify" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "pod_name",
    "query": "query_result(sum(api_service_health_called_count)by(name))"
   }
  ]
 },
 "panels": [
  { "title": "StandardMetics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Requests/s",
   "type": "singlestat",
   "description": "Numberofinboundrequestspersecond",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(envoy_http_downstream_rq_xx{envoy_http_conn_manager_prefix=~\"service:emojify-api|service:emojify-website\",label_app=\"emojify-ingress\",envoy_response_code_class=~\"2|4\"}[60s]))"
    }
   ]
  },
  {
   "title": "Errors/s",
   "type": "singlestat",
   "description": "Numberofoutbounderrorspersecond",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(envoy_http_downstream_rq_xx{envoy_http_conn_manager_prefix=~\"service:emojify-api|service:emojify-website\",label_app=\"emojify-ingress\",envoy_response_code_class=\"5\"}[60s]))"
    }
   ]
  },
  {
   "title": "PodCPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container_name!=\"POD\",pod_name=~\"emojify-ingress-.*\",name=~\"^k8s_.*\"}[1m]))by(container_name)",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "PodMemory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{container_name!=\"POD\",name=~\"^k8s_.*\",pod_name=~\"emojify-ingress-.*\"})by(container_name)",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "EnvoyListenerRequestsInbound(Downstream)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(envoy_http_downstream_rq_xx{envoy_http_conn_manager_prefix=~\"service:emojify-api|service:emojify-website\",label_app=\"emojify-ingress\"}[30s]))by(envoy_response_code_class)",
     "legendFormat": "{{envoy_response_code_class}}xx"
    }
   ]
  },
  {
   "title": "APIUpstreamRequests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(envoy_cluster_upstream_rq_xx{label_app=\"emojify-ingress\",envoy_cluster_name=\"service_emojify-api\"}[30s]))by(envoy_response_code_class)",
     "legendFormat": "{{envoy_response_code_class}}xx-"
    }
   ]
  },
  {
   "title": "WebsiteUpstreamRequests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(envoy_cluster_upstream_rq_xx{label_app=\"emojify-ingress\",envoy_cluster_name=\"service_emojify-website\"}[30s]))by(envoy_response_code_class)",
     "legendFormat": "{{envoy_response_code_class}}xxx"
    }
   ]
  },
  {
   "title": "APIRequests(ms)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_time_sum{envoy_cluster_name=\"service_emojify-api\"}[30s])/rate(envoy_cluster_upstream_rq_time_count{envoy_cluster_name=\"service_emojify-api\"}[30s]))",
     "legendFormat": "allpods"
    }
   ]
  },
  {
   "title": "WebsiteRequests(ms)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_time_sum{envoy_cluster_name=\"service_emojify-website\"}[30s])/rate(envoy_cluster_upstream_rq_time_count{envoy_cluster_name=\"service_emojify-website\"}[30s]))",
     "legendFormat": "allpods"
    }
   ]
  },
  { "title": "ReliabilityMetrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "APIUpstreamTimeouts",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(envoy_cluster_upstream_rq_timeout{label_app=\"emojify-ingress\",envoy_cluster_name=\"service_emojify-api\"}[30s]))",
     "legendFormat": "timeout"
    }
   ]
  },
  {
   "title": "WebsiteUpstreamTimeouts",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(envoy_cluster_upstream_rq_timeout{label_app=\"emojify-ingress\",envoy_cluster_name=\"service_emojify-website\"}[30s]))",
     "legendFormat": "timeout"
    }
   ]
  },
  {
   "title": "APIUpstreamRetries",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(envoy_cluster_retry_upstream_rq_xx{label_app=\"emojify-ingress\",envoy_cluster_name=\"service_emojify-api\"}[30s]))",
     "legendFormat": "retries"
    }
   ]
  },
  {
   "title": "WebsiteUpstreamRetries",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 53 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(envoy_cluster_retry_upstream_rq_xx{label_app=\"emojify-ingress\",envoy_cluster_name=\"service_emojify-website\"}[30s]))",
     "legendFormat": "retries"
    }
   ]
  },
  {
   "title": "APIOutlierEjections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(envoy_cluster_outlier_detection_ejections_active{envoy_cluster_name=\"service_emojify-api\"})by(label_app)",
     "legendFormat": "{{label_app}}"
    }
   ]
  },
  {
   "title": "WebsiteOutlierEjectionsActive",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 62 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "envoy_cluster_outlier_detection_ejections_active{envoy_cluster_name=\"service_emojify-website\"}",
     "legendFormat": "{{label_app}}"
    }
   ]
  }
 ]
}
{
 "title": "lab04-Kubernetesclustermonitoring(viaprometheus)",
 "description": "MonitorsKubernetesclusterusingprometheus.ShowsoverallclusterCPU/Memory/Filesystemusageaswellasindividualpod,containers,systemdservicesstatistics.UsescAdvisormetricsonly.",
 "tags": [ "kubernetes" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "Node",
    "query": "label_values(kubernetes_io_hostname)"
   }
  ]
 },
 "panels": [
  { "title": "NetworkI/Opressure", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "NetworkI/Opressure",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{kubernetes_io_hostname=~\"^$Node$\"}[1m]))",
     "legendFormat": "Received"
    },
    {
     "expr": "-sum(rate(container_network_transmit_bytes_total{kubernetes_io_hostname=~\"^$Node$\"}[1m]))",
     "legendFormat": "Sent"
    }
   ]
  },
  { "title": "Totalusage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Clustermemoryusage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 7 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{id=\"/\",kubernetes_io_hostname=~\"^$Node$\"})/sum(machine_memory_bytes{kubernetes_io_hostname=~\"^$Node$\"})*100"
    }
   ]
  },
  {
   "title": "ClusterCPUusage(1mavg)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 7 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{id=\"/\",kubernetes_io_hostname=~\"^$Node$\"}[1m]))/sum(machine_cpu_cores{kubernetes_io_hostname=~\"^$Node$\"})*100"
    }
   ]
  },
  {
   "title": "Clusterfilesystemusage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 7 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(container_fs_usage_bytes{device=~\"^/dev/[sv]d[a-z][1-9]$\",id=\"/\",kubernetes_io_hostname=~\"^$Node$\"})/sum(container_fs_limit_bytes{device=~\"^/dev/[sv]d[a-z][1-9]$\",id=\"/\",kubernetes_io_hostname=~\"^$Node$\"})*100"
    }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 12 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{id=\"/\",kubernetes_io_hostname=~\"^$Node$\"})"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 12 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(machine_memory_bytes{kubernetes_io_hostname=~\"^$Node$\"})"
    }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{id=\"/\",kubernetes_io_hostname=~\"^$Node$\"}[1m]))"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(machine_cpu_cores{kubernetes_io_hostname=~\"^$Node$\"})"
    }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 12 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(container_fs_usage_bytes{device=~\"^/dev/[sv]d[a-z][1-9]$\",id=\"/\",kubernetes_io_hostname=~\"^$Node$\"})"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 12 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(container_fs_limit_bytes{device=~\"^/dev/[sv]d[a-z][1-9]$\",id=\"/\",kubernetes_io_hostname=~\"^$Node$\"})"
    }
   ]
  },
  { "title": "PodsCPUusage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "PodsCPUusage(1mavg)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\",kubernetes_io_hostname=~\"^$Node$\"}[1m]))by(pod_name)",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "SystemservicesCPUusage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "SystemservicesCPUusage(1mavg)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "none", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{systemd_service_name!=\"\",kubernetes_io_hostname=~\"^$Node$\"}[1m]))by(systemd_service_name)",
       "legendFormat": "{{systemd_service_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "ContainersCPUusage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "ContainersCPUusage(1mavg)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "none", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\",container_name!=\"POD\",kubernetes_io_hostname=~\"^$Node$\"}[1m]))by(container_name,pod_name)",
       "legendFormat": "pod:{{pod_name}}|{{container_name}}"
      },
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{image!=\"\",name!~\"^k8s_.*\",kubernetes_io_hostname=~\"^$Node$\"}[1m]))by(kubernetes_io_hostname,name,image)",
       "legendFormat": "docker:{{kubernetes_io_hostname}}|{{image}}({{name}})"
      },
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{rkt_container_name!=\"\",kubernetes_io_hostname=~\"^$Node$\"}[1m]))by(kubernetes_io_hostname,rkt_container_name)",
       "legendFormat": "rkt:{{kubernetes_io_hostname}}|{{rkt_container_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "AllprocessesCPUusage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "AllprocessesCPUusage(1mavg)",
     "type": "graph",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "none", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{id!=\"/\",kubernetes_io_hostname=~\"^$Node$\"}[1m]))by(id)",
       "legendFormat": "{{id}}"
      }
     ]
    }
   ]
  },
  { "title": "Podsmemoryusage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Podsmemoryusage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{image!=\"\",name=~\"^k8s_.*\",kubernetes_io_hostname=~\"^$Node$\"})by(pod_name)",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Systemservicesmemoryusage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "Systemservicesmemoryusage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{systemd_service_name!=\"\",kubernetes_io_hostname=~\"^$Node$\"})by(systemd_service_name)",
       "legendFormat": "{{systemd_service_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Containersmemoryusage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "Containersmemoryusage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{image!=\"\",name=~\"^k8s_.*\",container_name!=\"POD\",kubernetes_io_hostname=~\"^$Node$\"})by(container_name,pod_name)",
       "legendFormat": "pod:{{pod_name}}|{{container_name}}"
      },
      {
       "expr": "sum(container_memory_working_set_bytes{image!=\"\",name!~\"^k8s_.*\",kubernetes_io_hostname=~\"^$Node$\"})by(kubernetes_io_hostname,name,image)",
       "legendFormat": "docker:{{kubernetes_io_hostname}}|{{image}}({{name}})"
      },
      {
       "expr": "sum(container_memory_working_set_bytes{rkt_container_name!=\"\",kubernetes_io_hostname=~\"^$Node$\"})by(kubernetes_io_hostname,rkt_container_name)",
       "legendFormat": "rkt:{{kubernetes_io_hostname}}|{{rkt_container_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Allprocessesmemoryusage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "panels": [
    {
     "title": "Allprocessesmemoryusage",
     "type": "graph",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 36 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{id!=\"/\",kubernetes_io_hostname=~\"^$Node$\"})by(id)",
       "legendFormat": "{{id}}"
      }
     ]
    }
   ]
  },
  { "title": "PodsnetworkI/O", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "PodsnetworkI/O(1mavg)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{image!=\"\",name=~\"^k8s_.*\",kubernetes_io_hostname=~\"^$Node$\"}[1m]))by(pod_name)",
     "legendFormat": "->{{pod_name}}"
    },
    {
     "expr": "-sum(rate(container_network_transmit_bytes_total{image!=\"\",name=~\"^k8s_.*\",kubernetes_io_hostname=~\"^$Node$\"}[1m]))by(pod_name)",
     "legendFormat": "<-{{pod_name}}"
    }
   ]
  },
  {
   "title": "ContainersnetworkI/O",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "collapsed": true,
   "panels": [
    {
     "title": "ContainersnetworkI/O(1mavg)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 45 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(container_network_receive_bytes_total{image!=\"\",name=~\"^k8s_.*\",kubernetes_io_hostname=~\"^$Node$\"}[1m]))by(container_name,pod_name)",
       "legendFormat": "->pod:{{pod_name}}|{{container_name}}"
      },
      {
       "expr": "-sum(rate(container_network_transmit_bytes_total{image!=\"\",name=~\"^k8s_.*\",kubernetes_io_hostname=~\"^$Node$\"}[1m]))by(container_name,pod_name)",
       "legendFormat": "<-pod:{{pod_name}}|{{container_name}}"
      },
      {
       "expr": "sum(rate(container_network_receive_bytes_total{image!=\"\",name!~\"^k8s_.*\",kubernetes_io_hostname=~\"^$Node$\"}[1m]))by(kubernetes_io_hostname,name,image)",
       "legendFormat": "->docker:{{kubernetes_io_hostname}}|{{image}}({{name}})"
      },
      {
       "expr": "-sum(rate(container_network_transmit_bytes_total{image!=\"\",name!~\"^k8s_.*\",kubernetes_io_hostname=~\"^$Node$\"}[1m]))by(kubernetes_io_hostname,name,image)",
       "legendFormat": "<-docker:{{kubernetes_io_hostname}}|{{image}}({{name}})"
      },
      {
       "expr": "sum(rate(container_network_transmit_bytes_total{rkt_container_name!=\"\",kubernetes_io_hostname=~\"^$Node$\"}[1m]))by(kubernetes_io_hostname,rkt_container_name)",
       "legendFormat": "->rkt:{{kubernetes_io_hostname}}|{{rkt_container_name}}"
      },
      {
       "expr": "-sum(rate(container_network_transmit_bytes_total{rkt_container_name!=\"\",kubernetes_io_hostname=~\"^$Node$\"}[1m]))by(kubernetes_io_hostname,rkt_container_name)",
       "legendFormat": "<-rkt:{{kubernetes_io_hostname}}|{{rkt_container_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "AllprocessesnetworkI/O",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "collapsed": true,
   "panels": [
    {
     "title": "AllprocessesnetworkI/O(1mavg)",
     "type": "graph",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 46 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(container_network_receive_bytes_total{id!=\"/\",kubernetes_io_hostname=~\"^$Node$\"}[1m]))by(id)",
       "legendFormat": "->{{id}}"
      },
      {
       "expr": "-sum(rate(container_network_transmit_bytes_total{id!=\"/\",kubernetes_io_hostname=~\"^$Node$\"}[1m]))by(id)",
       "legendFormat": "<-{{id}}"
      }
     ]
    }
   ]
  }
 ]
}
{
 "title": "lab04-Website",
 "tags": [ "emojify" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "pod_name",
    "query": "query_result(sum(envoy_http_downstream_cx_total{envoy_http_conn_manager_prefix=\"ingress_website\"})by(name))"
   }
  ]
 },
 "panels": [
  {
   "title": "PodCPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container_name!=\"POD\",pod_name=~\"emojify-website-.*\",name=~\"^k8s_.*\"}[1m]))by(container_name)",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "PodMemory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{container_name!=\"POD\",name=~\"^k8s_.*\",pod_name=~\"emojify-api-.*\"})by(container_name)",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "EnvoyAuthz",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(envoy_ext_authz_connect_authz_ok{label_app=\"emojify-website\"}[30s])",
     "legendFormat": "{{controller_name}}"
    },
    {
     "expr": "increase(envoy_ext_authz_connect_authz_error{label_app=\"emojify-website\"}[30s])",
     "legendFormat": "{{controller_name}}"
    }
   ]
  },
  {
   "title": "EnvoyConnectionsInbound(downstream)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(envoy_http_downstream_cx_total{envoy_http_conn_manager_prefix=\"ingress_website\",name=~\"^$pod_name$\"}[1m]))",
     "legendFormat": "total"
    },
    {
     "expr": "sum(increase(envoy_http_downstream_cx_active{envoy_http_conn_manager_prefix=\"ingress_website\",name=~\"^$pod_name$\"}[1m]))",
     "legendFormat": "active"
    },
    {
     "expr": "sum(increase(envoy_http_downstream_cx_destroy_remote{envoy_http_conn_manager_prefix=\"ingress_website\",name=~\"^$pod_name$\"}[1m]))",
     "legendFormat": "destroy-remote"
    },
    {
     "expr": "sum(increase(envoy_http_downstream_cx_destroy_local{envoy_http_conn_manager_prefix=\"ingress_website\",name=~\"^$pod_name$\"}[1m]))",
     "legendFormat": "destroy-local"
    }
   ]
  },
  {
   "title": "EnvoyDownstreamRequests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(envoy_http_downstream_rq_xx{envoy_http_conn_manager_prefix=\"ingress_website\"}[30s]))by(controller_name,envoy_response_code_class)",
     "legendFormat": "{{controller_name}}-{{envoy_response_code_class}}xx"
    }
   ]
  }
 ]
}