{
 "title": "lab04 - API",
 "tags": [ "emojify" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "pod_name",
    "query": "query_result(sum(api_service_health_called_count) by (name))"
   }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "API errors/s",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(api_service_emojify_called_count{status!=\"200\"}[1m])+rate(api_service_cache_called_count{status!=\"200\"}[1m]))+sum(rate(api_service_error_injected[1m]))"
    }
   ]
  },
  {
   "title": "API requests/s",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(api_service_emojify_called_count{status=\"200\"}[1m])+rate(api_service_cache_called_count{status=\"200\"}[1m]))",
     "legendFormat": "Success"
    }
   ]
  },
  {
   "title": "Pod CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate (container_cpu_usage_seconds_total{container_name!=\"POD\",pod_name=~\"emojify-api-.*\",name=~\"^k8s_.*\"}[1m])) by(container_name)"
    }
   ]
  },
  {
   "title": "POD Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{container_name!=\"POD\",name=~\"^k8s_.*\",pod_name=~\"emojify-api-.*\"}) by (container_name)"
    }
   ]
  },
  { "title": "Envoy Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Envoy Authz",
   "type": "graph",
   "gridPos": { "h": 9, "w": 19, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(envoy_ext_authz_connect_authz_ok{label_app=\"emojify-api\", name=~\"^$pod_name$\"}[1m]))",
     "legendFormat": "ok"
    },
    {
     "expr": "sum(increase(envoy_ext_authz_connect_authz_error{label_app=\"emojify-api\", name=~\"^$pod_name$\"}[1m]))",
     "legendFormat": "error"
    }
   ]
  },
  {
   "title": "Envoy Authz Error",
   "type": "text",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 19 },
   "content": "# Authz\nEnvoy will close a connection which either timesout or returns an error state: [https://github.com/envoyproxy/envoy/issues/5023](https://github.com/envoyproxy/envoy/issues/5023)\n",
   "targets": [
    {
     "expr": "envoy_ext_authz_connect_authz_error"
    }
   ]
  },
  {
   "title": "Envoy Connections - downstream",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(envoy_http_downstream_cx_total{envoy_http_conn_manager_prefix=\"ingress_api\", name=~\"^$pod_name$\"}[1m]))",
     "legendFormat": "total"
    },
    {
     "expr": "sum(increase(envoy_http_downstream_cx_active{envoy_http_conn_manager_prefix=\"ingress_api\", name=~\"^$pod_name$\"}[1m]))",
     "legendFormat": "active"
    },
    {
     "expr": "sum(increase(envoy_http_downstream_cx_destroy_remote{envoy_http_conn_manager_prefix=\"ingress_api\", name=~\"^$pod_name$\"}[1m]))",
     "legendFormat": "destroy-remote"
    },
    {
     "expr": "sum(increase(envoy_http_downstream_cx_destroy_local{envoy_http_conn_manager_prefix=\"ingress_api\", name=~\"^$pod_name$\"}[1m]))",
     "legendFormat": "destroy-local"
    }
   ]
  },
  {
   "title": "Envoy Inbound Requests (downstream)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(envoy_http_downstream_rq_xx{envoy_http_conn_manager_prefix=\"ingress_api\", name=~\"^$pod_name$\"}[30s])) by (envoy_response_code_class,name)",
     "legendFormat": "{{envoy_response_code_class}}xx-{{name}}"
    }
   ]
  },
  {
   "title": "Envoy Connections Data Transferred (per second)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_http_downstream_cx_tx_bytes_total{envoy_http_conn_manager_prefix=\"ingress_api\", name=~\"^$pod_name$\"}[30s])) by (name)",
     "legendFormat": "{{envoy_response_code_class}}xx-{{name}}"
    }
   ]
  },
  { "title": "Application Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "Emojify API Request Duration /cache GET(ms)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(rate(api_service_cache_called_sum{name=~\"^$pod_name$\"}[10s])/rate(api_service_cache_called_count{name=~\"^$pod_name$\"}[10s])) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Emojify API Request Duration / POST (ms)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(rate(api_service_emojify_called_sum{name=~\"^$pod_name$\"}[30s])/rate(api_service_emojify_called_count{name=~\"^$pod_name$\"}[30s])) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Emojify API Request Duration /health GET (ms)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(rate(api_service_health_called_sum{name=~\"^$pod_name$\"}[1m])/rate(api_service_health_called_count{name=~\"^$pod_name$\"}[1m])) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Emojify Face Detect Duration",
   "type": "graph",
   "description": "Time taken for upstream facebox API to detect faces in an image",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 80 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(rate(api_service_emojify_find_faces_sum{name=~\"^$pod_name$\"}[30s])/rate(api_service_emojify_find_faces_count{name=~\"^$pod_name$\"}[30s])) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Emojify Cache Hits",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 88 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(api_service_emojify_cache_check_count{name=~\"^$pod_name$\"}[30s])) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Health Checks",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 96 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(api_service_health_called_count[1m])",
     "legendFormat": "{{ip}}"
    }
   ]
  }
 ]
}