{
 "title": "lab04 - Cache",
 "tags": [ "emojify" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "pod_name",
    "query": "query_result(sum(cache_service_cache_get) by (name))"
   }
  ]
 },
 "panels": [
  { "title": "General Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cache requests / s",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(cache_service_cache_get_count{status=\"200\"}[60s])+rate(cache_service_cache_put_count{status=\"200\"}[60s]))+sum(rate(cache_service_cache_exists_count{status=\"302\"}[60s]))"
    }
   ]
  },
  {
   "title": "Errors/s",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(cache_service_cache_exists{status=~\"5.*\"}[60s])+rate(cache_service_cache_put{status=~\"5.*\"}[60s])+rate(cache_service_cache_get{status=~\"5.*\"}[60s]))+sum(rate(cache_service_cache_exists_count{status=~\"5.*\"}[60s]))"
    }
   ]
  },
  {
   "title": "Pod CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum(rate (container_cpu_usage_seconds_total{container_name!=\"POD\",pod_name=~\"emojify-cache-.*\",name=~\"^k8s_.*\"}[1m])) by(container_name)",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "Pod Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{container_name!=\"POD\",name=~\"^k8s_.*\",pod_name=~\"emojify-cache-.*\"}) by (container_name)",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "Envoy Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true
  },
  {
   "title": "Current Envoy Upstream Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(envoy_http_downstream_cx_total{envoy_http_conn_manager_prefix=\"ingress_cache\", name=~\"^$pod_name$\"}[1m])",
     "legendFormat": "total"
    },
    {
     "expr": "sum(increase(envoy_http_downstream_cx_active{envoy_http_conn_manager_prefix=\"ingress_cache\", name=~\"^$pod_name$\"}[1m]))",
     "legendFormat": "active"
    },
    {
     "expr": "sum(increase(envoy_http_downstream_cx_destroy_remote{envoy_http_conn_manager_prefix=\"ingress_cache\", name=~\"^$pod_name$\"}[1m]))",
     "legendFormat": "destroy-remote"
    },
    {
     "expr": "sum(increase(envoy_http_downstream_cx_destroy_local{envoy_http_conn_manager_prefix=\"ingress_cache\", name=~\"^$pod_name$\"}[1m]))",
     "legendFormat": "destroy-local"
    }
   ]
  },
  {
   "title": "Envoy Authz",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(envoy_ext_authz_connect_authz_ok{name=~\"emojify-cache.*\"}[30s])",
     "legendFormat": "{{name}}-ok"
    },
    {
     "expr": "rate(envoy_ext_authz_connect_authz_error{name=~\"emojify-cache.*\"}[30s])",
     "legendFormat": "{{name}}-error"
    }
   ]
  },
  {
   "title": "Cache Success gRPC",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(envoy_cluster_grpc_0{label_app=\"emojify-cache\"}[30s])) by (envoy_grpc_bridge_method)",
     "legendFormat": "{{envoy_grpc_bridge_method}}"
    }
   ]
  },
  {
   "title": "Cache Failure gRPC",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(envoy_cluster_grpc_failure{label_app=\"emojify-cache\"}[30s])) by (envoy_grpc_bridge_method)",
     "legendFormat": "{{envoy_grpc_bridge_method}}"
    }
   ]
  },
  {
   "title": "Cache Not Found gRPC",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(envoy_cluster_grpc_5{label_app=\"emojify-cache\"}[30s])) by(envoy_grpc_bridge_method)",
     "legendFormat": "{{envoy_grpc_bridge_method}}"
    }
   ]
  },
  { "title": "Application Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 } },
  {
   "title": "Cache Get (ms)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rate(cache_service_cache_get_sum[30s])/rate(cache_service_cache_get_count[30s])",
     "legendFormat": "{{name}}-{{status}}"
    }
   ]
  },
  {
   "title": "Cache Put (ms)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rate(cache_service_cache_put_sum[30s])/rate(cache_service_cache_put_count[30s])",
     "legendFormat": "{{name}}-{{status}}"
    }
   ]
  },
  {
   "title": "Cache invalidation (ms)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "cache_service_cache_invalidate_sum/cache_service_cache_invalidate_count",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Cache Invalidated Items",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 72 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(cache_service_cache_invalidated[30s])",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}