{
 "title": "lab04 - Ingress",
 "tags": [ "emojify" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "pod_name",
    "query": "query_result(sum(api_service_health_called_count) by (name))"
   }
  ]
 },
 "panels": [
  { "title": "Standard Metics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Requests / s",
   "type": "singlestat",
   "description": "Number of inbound requests per second",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(envoy_http_downstream_rq_xx{envoy_http_conn_manager_prefix=~\"service:emojify-api|service:emojify-website\",label_app=\"emojify-ingress\", envoy_response_code_class=~\"2|4\"}[60s]))"
    }
   ]
  },
  {
   "title": "Errors / s",
   "type": "singlestat",
   "description": "Number of outbound errors per second",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(envoy_http_downstream_rq_xx{envoy_http_conn_manager_prefix=~\"service:emojify-api|service:emojify-website\",label_app=\"emojify-ingress\", envoy_response_code_class=\"5\"}[60s]))"
    }
   ]
  },
  {
   "title": "Pod CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate (container_cpu_usage_seconds_total{container_name!=\"POD\",pod_name=~\"emojify-ingress-.*\",name=~\"^k8s_.*\"}[1m])) by(container_name)",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "Pod Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{container_name!=\"POD\",name=~\"^k8s_.*\",pod_name=~\"emojify-ingress-.*\"}) by (container_name)",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "Envoy Listener Requests Inbound (Downstream)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(envoy_http_downstream_rq_xx{envoy_http_conn_manager_prefix=~\"service:emojify-api|service:emojify-website\",label_app=\"emojify-ingress\"}[30s])) by (envoy_response_code_class)",
     "legendFormat": "{{envoy_response_code_class}}xx"
    }
   ]
  },
  {
   "title": "API Upstream Requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(envoy_cluster_upstream_rq_xx{label_app=\"emojify-ingress\",envoy_cluster_name=\"service_emojify-api\"}[30s])) by (envoy_response_code_class)",
     "legendFormat": "{{envoy_response_code_class}}xx-"
    }
   ]
  },
  {
   "title": "Website Upstream Requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(envoy_cluster_upstream_rq_xx{label_app=\"emojify-ingress\",envoy_cluster_name=\"service_emojify-website\"}[30s])) by (envoy_response_code_class)",
     "legendFormat": "{{envoy_response_code_class}}xxx"
    }
   ]
  },
  {
   "title": "API Requests (ms)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_time_sum{envoy_cluster_name=\"service_emojify-api\"}[30s])/rate(envoy_cluster_upstream_rq_time_count{envoy_cluster_name=\"service_emojify-api\"}[30s]))",
     "legendFormat": "all pods"
    }
   ]
  },
  {
   "title": "Website Requests (ms)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_time_sum{envoy_cluster_name=\"service_emojify-website\"}[30s])/rate(envoy_cluster_upstream_rq_time_count{envoy_cluster_name=\"service_emojify-website\"}[30s]))",
     "legendFormat": "all pods"
    }
   ]
  },
  { "title": "Reliability Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "API Upstream Timeouts",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(envoy_cluster_upstream_rq_timeout{label_app=\"emojify-ingress\",envoy_cluster_name=\"service_emojify-api\"}[30s]))",
     "legendFormat": "timeout"
    }
   ]
  },
  {
   "title": "Website Upstream Timeouts",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(envoy_cluster_upstream_rq_timeout{label_app=\"emojify-ingress\",envoy_cluster_name=\"service_emojify-website\"}[30s]))",
     "legendFormat": "timeout"
    }
   ]
  },
  {
   "title": "API Upstream Retries",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(envoy_cluster_retry_upstream_rq_xx{label_app=\"emojify-ingress\",envoy_cluster_name=\"service_emojify-api\"}[30s]))",
     "legendFormat": "retries"
    }
   ]
  },
  {
   "title": "Website Upstream Retries",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 53 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(envoy_cluster_retry_upstream_rq_xx{label_app=\"emojify-ingress\",envoy_cluster_name=\"service_emojify-website\"}[30s]))",
     "legendFormat": "retries"
    }
   ]
  },
  {
   "title": "API Outlier Ejections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(envoy_cluster_outlier_detection_ejections_active{envoy_cluster_name=\"service_emojify-api\"}) by (label_app)",
     "legendFormat": "{{label_app}}"
    }
   ]
  },
  {
   "title": "Website Outlier Ejections Active",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 62 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "envoy_cluster_outlier_detection_ejections_active{envoy_cluster_name=\"service_emojify-website\"}",
     "legendFormat": "{{label_app}}"
    }
   ]
  }
 ]
}