{
 "title": "lab04 - Website",
 "tags": [ "emojify" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "pod_name",
    "query": "query_result(sum(envoy_http_downstream_cx_total{envoy_http_conn_manager_prefix=\"ingress_website\"}) by (name))"
   }
  ]
 },
 "panels": [
  {
   "title": "Pod CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate (container_cpu_usage_seconds_total{container_name!=\"POD\",pod_name=~\"emojify-website-.*\",name=~\"^k8s_.*\"}[1m])) by(container_name)",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "Pod Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{container_name!=\"POD\",name=~\"^k8s_.*\",pod_name=~\"emojify-api-.*\"}) by (container_name)",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "Envoy Authz",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(envoy_ext_authz_connect_authz_ok{label_app=\"emojify-website\"}[30s])",
     "legendFormat": "{{controller_name}}"
    },
    {
     "expr": "increase(envoy_ext_authz_connect_authz_error{label_app=\"emojify-website\"}[30s])",
     "legendFormat": "{{controller_name}}"
    }
   ]
  },
  {
   "title": "Envoy Connections Inbound (downstream)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(envoy_http_downstream_cx_total{envoy_http_conn_manager_prefix=\"ingress_website\", name=~\"^$pod_name$\"}[1m]))",
     "legendFormat": "total"
    },
    {
     "expr": "sum(increase(envoy_http_downstream_cx_active{envoy_http_conn_manager_prefix=\"ingress_website\", name=~\"^$pod_name$\"}[1m]))",
     "legendFormat": "active"
    },
    {
     "expr": "sum(increase(envoy_http_downstream_cx_destroy_remote{envoy_http_conn_manager_prefix=\"ingress_website\", name=~\"^$pod_name$\"}[1m]))",
     "legendFormat": "destroy-remote"
    },
    {
     "expr": "sum(increase(envoy_http_downstream_cx_destroy_local{envoy_http_conn_manager_prefix=\"ingress_website\", name=~\"^$pod_name$\"}[1m]))",
     "legendFormat": "destroy-local"
    }
   ]
  },
  {
   "title": "Envoy Downstream Requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(envoy_http_downstream_rq_xx{envoy_http_conn_manager_prefix=\"ingress_website\"}[30s])) by (controller_name,envoy_response_code_class)",
     "legendFormat": "{{controller_name}}-{{envoy_response_code_class}}xx"
    }
   ]
  }
 ]
}