---
apiVersion: v1
kind: Secret
metadata:
  name: emojify
type: Opaque
data:
  mb_key: YW1GamEzTnZiaTV1YVdOQVoyMWhhV3d1WTI5dC40OW90b0MxRzNPcDRQS1NRbFlZQzMyVExmMXkxWGRpbjhBODIzenNOM3ZSblBzcDY1MFVSXzJYUVNKWklVbnltSV9CSTl5d0FwV01Jdnlwd0pwNU5XZwo= 
